#!/usr/bin/env python3
"""Task specs for the two follow-up experiments the first pass left open.

**clinc150-described-full** -- the clean version of the description experiment.
The original (E1b) described only the 16 classes that had been seen to fail,
which caps its result at "upper bound". Here every one of the 150 classes gets a
description generated by one mechanical rule applied uniformly: the class's
first three utterances in the *training* split, in file order, quoted verbatim.
No per-class judgement, no reference to which classes erred. Because the
exemplars come from train, evaluation is on val+test only (7,500 rows), so the
description source and the scored rows are disjoint; the bare-name baseline is
the E1 run restricted to the same 7,500 rows.

**clinc150-gate-rich** -- the noul scope gate again, but with the scope stated
extensionally: the instructions enumerate all 150 intent names instead of
gesturing at "150 everyday personal-assistant intents" in one sentence. E3's
boolean lost to E2's Choice five-fold as an out-of-scope detector, but E2 also
saw the full option list; this run gives the boolean the same information, which
separates "the primitive is weaker" from "the question was under-specified".
Rows identical to E3.

    python scripts/build_followups.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

ROOT = Path(__file__).resolve().parent.parent
TASKS = ROOT / "tasks"
EXEMPLARS_PER_CLASS = 3


def main() -> int:
    data = json.loads((ROOT / "data" / "data_full.json").read_text())

    # ---- described-full ------------------------------------------------------
    exemplars: dict[str, list[str]] = {}
    for text, intent in data["train"]:
        bucket = exemplars.setdefault(intent, [])
        if len(bucket) < EXEMPLARS_PER_CLASS:
            bucket.append(text)
    criteria = {intent: 'e.g. "' + '" / "'.join(rows) + '"'
                for intent, rows in sorted(exemplars.items())}

    base = json.loads((TASKS / "clinc150-inscope.json").read_text())
    rows = [json.loads(l) for l in (TASKS / "clinc150-inscope.jsonl").open()]
    eval_rows = [r for r in rows if r["split"] in ("val", "test")]
    with (TASKS / "clinc150-described-full.jsonl").open("w") as fh:
        for r in eval_rows:
            fh.write(json.dumps(r) + "\n")
    spec = dict(base)
    spec.update({
        "name": "clinc150-described-full",
        "criteria": criteria,
        "data": "clinc150-described-full.jsonl",
        "notes": (
            "The clean description experiment: every class described by one rule "
            "fixed in advance and applied uniformly -- its first "
            f"{EXEMPLARS_PER_CLASS} training utterances, in file order, verbatim. "
            "Evaluated on val+test only, so the exemplar source and the scored "
            "rows are disjoint. Baseline: the bare-name E1 run on the same rows."
        ),
    })
    (TASKS / "clinc150-described-full.json").write_text(json.dumps(spec, indent=2) + "\n")
    print(f"clinc150-described-full: {len(eval_rows):,} rows, "
          f"{len(criteria)} described classes")

    # ---- gate-rich -----------------------------------------------------------
    gate = json.loads((TASKS / "clinc150-gate.json").read_text())
    names = ", ".join(i.replace("_", " ") for i in sorted(exemplars))
    rich = dict(gate)
    rich.update({
        "name": "clinc150-gate-rich",
        "instructions": (
            "The assistant handles exactly these request types, and nothing else: "
            f"{names}. Answer true if the utterance is a request of one of those "
            "types, and false if it falls outside all of them."
        ),
        "data": "clinc150-gate.jsonl",
        "notes": (
            "Identical rows to clinc150-gate; the only change is that the scope is "
            "enumerated (all 150 intent names) rather than described in one "
            "sentence. Separates the noul primitive's capability from the "
            "under-specification of the original instruction."
        ),
    })
    (TASKS / "clinc150-gate-rich.json").write_text(json.dumps(rich, indent=2) + "\n")
    print("clinc150-gate-rich: 2,400 rows, scope enumerated "
          f"({len(exemplars)} intent names in the instructions)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
